package org.tzi.use.plugins.jacamo.runtime;

public enum RuntimeEventKind {
    CREATE_OBJECT, DESTROY_OBJECT, SET_ATTRIBUTE, INSERT_LINK, DELETE_LINK, REPLACE_ORDER,
    OP_ENTER, OP_EXIT, OP_FAIL,
    BELIEF_ADDED, BELIEF_REMOVED,
    GOAL_ADOPTED, GOAL_REMOVED, GOAL_ACHIEVED, GOAL_FAILED,
    ACTION_STARTED, ACTION_SUCCEEDED, ACTION_FAILED,
    MESSAGE_SENT, MESSAGE_RECEIVED,
    ARTIFACT_CREATED, ARTIFACT_DISPOSED,
    OBS_PROPERTY_ADDED, OBS_PROPERTY_CHANGED, OBS_PROPERTY_REMOVED, SIGNAL,
    ORGANISATION_DISCOVERED, GROUP_CREATED, GROUP_DISPOSED, SCHEME_CREATED, SCHEME_DISPOSED,
    ROLE_ADOPTED, ROLE_REMOVED, MISSION_COMMITTED, MISSION_REMOVED,
    SCHEME_STATE_CHANGED, NORM_STATE_CHANGED
}
