package org.jacamo.bridge.contract;

public enum RuntimeEventKind {
    CREATED, DISPOSED, ADDED, REMOVED, CHANGED, STARTED, SUCCEEDED, FAILED,
    FOCUSED, UNFOCUSED, JOINED, QUIT, COMMITTED, DECOMMITTED,
    GOAL_STATE_CHANGED, NORM_ACTIVATED, NORM_FULFILLED, NORM_UNFULFILLED,
    NORM_INACTIVATED, MODEL_REVISION_CHANGED, GAP
}
