package org.jacamo.bridge.contract;

public enum RuntimeFactKind {
    AGENT, BELIEF, GOAL, PLAN, WORKSPACE, ARTIFACT, OPERATION, PROPERTY,
    GROUP_BOARD, SCHEME_BOARD, ROLE_PLAYER, MISSION_COMMITMENT,
    ORGANISATIONAL_GOAL_STATE, NORM_INSTANCE, RELATION_STATE
}
