package org.tzi.use.plugins.jacamo.diagnostics;

public enum Phase { PROJECT_DISCOVERY, PARSING, RESOLUTION, SEMANTIC_MODEL, MAPPING, MATERIALIZATION,
    CONSTRAINT_TRANSLATION, VERIFICATION, RUNTIME }
