!create worker : Agent
!create ready : Belief
!create body_2 : Body
!create context_2 : Context
!create setValue : ExternalAction
!create plan_2 : Plan
!create start : TriggeringEvent
!create counter1 : Counter
!create valid : GuardOperation
!create count : ObsProperty
!create guardedSet : Operation
!create setValue_f39b1330 : Operation
!create world : Workspace
!create functional : FunctionalSpecification
!create team_group : Group
!create count_76e5738e : Mission
!create can_count : Norm
!create normative : NormativeSpecification
!create count_items : OGoal
!create team : Organisation
!create worker_742281e1 : Role
!create counting : Scheme
!create structural : StructuralSpecification
!create counter_team : MAS
!set worker.Name := 'worker'
!set ready.Name := 'ready'
!set ready.isInitial := true
!set body_2.Name := 'body@2'
!set context_2.Expression := 'ready'
!set setValue.Expression := 'setValue(1)'
!set setValue.Name := 'setValue'
!set plan_2.Name := 'plan@2'
!set start.Expression := 'start'
!set counter1.className := 'demo.Counter'
!set counter1.count := 0
!set valid.className := 'demo.Counter'
!set count.Name := 'count'
!set guardedSet.className := 'demo.Counter'
!set setValue_f39b1330.className := 'demo.Counter'
!set world.Name := 'world'
!set team_group.Name := 'team_group'
!set team_group.max := 1
!set team_group.min := 1
!set count_76e5738e.max := 1
!set count_76e5738e.min := 1
!set can_count.type := 'permission'
!set count_items.Name := 'count_items'
!set count_items.isRootGoal := true
!set team.id := 'team'
!set worker_742281e1.Name := 'worker'
!set worker_742281e1.max := 1
!set worker_742281e1.min := 1
!set counter_team.Name := 'counter_team'
!insert (worker,counter1) into Agent_artifact_Artifact
!insert (worker,ready) into Agent_belief_Belief
!insert (worker,plan_2) into Agent_plan_Plan
!insert (counter1,count) into Artifact_obsproperty_ObsProperty
!insert (counter1,guardedSet) into Artifact_operation_AbsOperation
!insert (counter1,setValue_f39b1330) into Artifact_operation_AbsOperation
!insert (counter1,valid) into Artifact_operation_AbsOperation
!insert (body_2,setValue) into Body_firstAction_Action
!insert (setValue,setValue_f39b1330) into ExternalAction_operation_AbsOperation
!insert (functional,counting) into FunctionalSpecification_scheme_Scheme
!insert (team_group,worker_742281e1) into Group_RefRole_Role
!insert (counter_team,worker) into MAS_agent_Agent
!insert (counter_team,team) into MAS_organisation_Organisation
!insert (counter_team,world) into MAS_workspace_Workspace
!insert (count_76e5738e,count_items) into Mission_ogoal_OGoal
!insert (can_count,count_76e5738e) into Norm_NMission_Mission
!insert (can_count,worker_742281e1) into Norm_Nrole_Role
!insert (normative,can_count) into NormativeSpecification_norm_Norm
!insert (guardedSet,valid) into Operation_guardedBy_GuardOperation
!insert (team,worker) into Organisation_deploysAgent_Agent
!insert (team,functional) into Organisation_functionalspecification_FunctionalSpecification
!insert (team,normative) into Organisation_normativespecification_NormativeSpecification
!insert (team,structural) into Organisation_structuralspecification_StructuralSpecification
!insert (plan_2,setValue) into Plan_hasAction_Action
!insert (plan_2,body_2) into Plan_hasBody_Body
!insert (plan_2,context_2) into Plan_hasContext_Context
!insert (worker_742281e1,worker) into Role_players_Agent
!insert (counting,count_items) into Scheme_SchemeOgoal_OGoal
!insert (counting,count_76e5738e) into Scheme_mission_Mission
!insert (structural,team_group) into StructuralSpecification_group_Group
!insert (structural,worker_742281e1) into StructuralSpecification_role_Role
!insert (start,plan_2) into TriggeringEvent_triggersPlan_Plan
!insert (world,counter1) into Workspace_artifact_Artifact
