!create auctioneer : Agent
!create auction_open : Belief
!create budget : Belief
!create body_5 : Body
!create context_5 : Context
!create placeBid : ExternalAction
!create start : Goal
!create send : Message
!create plan_5 : Plan
!create affordable : Rule
!create start_f4cda041 : TriggeringEvent
!create auction1 : AuctionArtifact
!create canBid : GuardOperation
!create open : ObsProperty
!create closeAuction : Operation
!create placeBid_fa9c4c3c : Operation
!create removeOpen : Operation
!create market : Workspace
!create formation_1 : FormationConstraints
!create functional : FunctionalSpecification
!create auction_group : Group
!create link_1 : Link
!create run_auction : Mission
!create n1 : Norm
!create normative : NormativeSpecification
!create sell_item : OGoal
!create oplan_1 : OPlan
!create auction_org : Organisation
!create auctioneer_9e3af946 : Role
!create auction_scheme : Scheme
!create structural : StructuralSpecification
!create auction : MAS
!set auctioneer.Name := 'auctioneer'
!set auction_open.Name := 'auction_open'
!set auction_open.isInitial := true
!set budget.Name := 'budget'
!set budget.isInitial := true
!set body_5.Name := 'body@5'
!set context_5.Expression := 'auction_open'
!set placeBid.Expression := 'placeBid(item1, 10)'
!set placeBid.Name := 'placeBid'
!set start.Name := 'start'
!set send.Expression := '.send(observer,tell,bid_placed(item1))'
!set send.Name := 'send'
!set send.content := '.send(observer,tell,bid_placed(item1))'
!set send.isBroadcast := false
!set plan_5.Name := 'plan@5'
!set affordable.Expression := 'budget(B) & B >= A'
!set start_f4cda041.Expression := 'start'
!set auction1.className := 'auction.AuctionArtifact'
!set auction1.open := true
!set canBid.className := 'auction.AuctionArtifact'
!set open.Name := 'open'
!set closeAuction.className := 'auction.AuctionArtifact'
!set placeBid_fa9c4c3c.className := 'auction.AuctionArtifact'
!set placeBid_fa9c4c3c.signalExpression := 'signal("bid", item, amount)'
!set removeOpen.className := 'auction.AuctionArtifact'
!set market.Name := 'market'
!set formation_1.Name := 'formation@1'
!set auction_group.Name := 'auction_group'
!set auction_group.max := 1
!set auction_group.min := 1
!set link_1.biDir := true
!set link_1.ecore_Link_from := 'auctioneer'
!set link_1.scope := 'intra-group'
!set link_1.to := 'auctioneer'
!set link_1.type := 'communication'
!set run_auction.max := 1
!set run_auction.min := 1
!set n1.timeConstraint := 'before auction closes'
!set n1.type := 'obligation'
!set sell_item.Name := 'sell_item'
!set sell_item.isRootGoal := true
!set oplan_1.Parallel := false
!set oplan_1.ecore_OPlan_Sequence := true
!set auction_org.id := 'auction_org'
!set auctioneer_9e3af946.Name := 'auctioneer'
!set auctioneer_9e3af946.max := 1
!set auctioneer_9e3af946.min := 1
!set auction.Name := 'auction'
!insert (placeBid,send) into Action_nextAction_Action
!insert (auctioneer,auction1) into Agent_artifact_Artifact
!insert (auctioneer,auction_open) into Agent_belief_Belief
!insert (auctioneer,budget) into Agent_belief_Belief
!insert (auctioneer,start) into Agent_hasGoal_Goal
!insert (auctioneer,plan_5) into Agent_plan_Plan
!insert (auctioneer,affordable) into Agent_rule_Rule
!insert (auction1,open) into Artifact_obsproperty_ObsProperty
!insert (auction1,canBid) into Artifact_operation_AbsOperation
!insert (auction1,closeAuction) into Artifact_operation_AbsOperation
!insert (auction1,placeBid_fa9c4c3c) into Artifact_operation_AbsOperation
!insert (auction1,removeOpen) into Artifact_operation_AbsOperation
!insert (body_5,placeBid) into Body_firstAction_Action
!insert (placeBid,placeBid_fa9c4c3c) into ExternalAction_operation_AbsOperation
!insert (functional,auction_scheme) into FunctionalSpecification_scheme_Scheme
!insert (start,start_f4cda041) into Goal_triggeredBy_TriggeringEvent
!insert (auction_group,auctioneer_9e3af946) into Group_RefRole_Role
!insert (auction_group,formation_1) into Group_formationconstraints_FormationConstraints
!insert (auction_group,link_1) into Group_link_Link
!insert (auction,auctioneer) into MAS_agent_Agent
!insert (auction,auction_org) into MAS_organisation_Organisation
!insert (auction,market) into MAS_workspace_Workspace
!insert (run_auction,sell_item) into Mission_ogoal_OGoal
!insert (n1,run_auction) into Norm_NMission_Mission
!insert (n1,auctioneer_9e3af946) into Norm_Nrole_Role
!insert (normative,n1) into NormativeSpecification_norm_Norm
!insert (oplan_1,sell_item) into OPlan_FirstOgoal_OGoal
!insert (placeBid_fa9c4c3c,canBid) into Operation_guardedBy_GuardOperation
!insert (auction_org,auctioneer) into Organisation_deploysAgent_Agent
!insert (auction_org,functional) into Organisation_functionalspecification_FunctionalSpecification
!insert (auction_org,normative) into Organisation_normativespecification_NormativeSpecification
!insert (auction_org,structural) into Organisation_structuralspecification_StructuralSpecification
!insert (plan_5,placeBid) into Plan_hasAction_Action
!insert (plan_5,send) into Plan_hasAction_Action
!insert (plan_5,body_5) into Plan_hasBody_Body
!insert (plan_5,context_5) into Plan_hasContext_Context
!insert (auctioneer_9e3af946,auctioneer) into Role_players_Agent
!insert (auction_scheme,oplan_1) into Scheme_SchemeOPlan_OPlan
!insert (auction_scheme,sell_item) into Scheme_SchemeOgoal_OGoal
!insert (auction_scheme,run_auction) into Scheme_mission_Mission
!insert (structural,auction_group) into StructuralSpecification_group_Group
!insert (structural,auctioneer_9e3af946) into StructuralSpecification_role_Role
!insert (start_f4cda041,plan_5) into TriggeringEvent_triggersPlan_Plan
!insert (market,auction1) into Workspace_artifact_Artifact
